import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
   "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[font]
size = 24.0
#use_thin_strokes = true

[font.bold]
family = "Hack Nerd Font Mono"

[font.italic]
family = "Hack Nerd Font Mono"

[font.normal]
family = "Hack Nerd Font Mono"

[font.offset]
x = 0
y = 5

[window]
#decorations = "Buttonless"
decorations = "full"
opacity = 0.6
blur = true

[window.padding]
x = 0
y = 0
